type Query {
    trade(id: Long!): Trade
    user(id: Long!): User
    organization(id: Long!): Organization
    trades(limit: Int, skip: Int, tradeQueryDto: TradeQueryDtoInput): PartialResults_Trade
}

type Mutation {
    authenticate(dto: AuthenticateDtoInput): AuthenticatePayload
}

type Trade {
    id: Long
    title: String
    completionDate: Long
    status: TradeStatus
    organizer: Organization
    lots: [Lot]
    registeredNumber: String
    targetUser: User
    procurementClassifier: [ProcurementClassifier]
    destinationRegion: [KLADRClassifier]
    procurementMethod: ProcurementMethod
    tradeReasoning: String
    participationConfirmationStartDate: Long
    participationConfirmationEndDate: Long
    bidSubmissionStartDate: Long
    bidSubmissionEndDate: Long
}

type PurchaseItem {
    id: Long
    title: String
    procurementClassifier: [ProcurementClassifier]
    quantity: BigDecimal
    unit: Unit
    code: String
    price: BigDecimal
}

type Unit {
    code: String
    id: Long
    title: String
}

type KLADRClassifier {
    code: String
    fullTitle: String
    id: Long
    title: String
}

type ProcurementClassifier {
    title: String
    code: String
    id: Long
}

type ProcurementMethod {
    code: String
    id: Long
    title: String
}

type Group {
    code: String
    id: Long
    members: [User]
    title: String
}

type Lot {
    id: Long
    initialContractPrice: BigDecimal
    title: String
    vatType: VatType
    purchaseItems: [PurchaseItem]
    currency: Currency
}

enum VatType {
    EXCLUDED
    EXCLUDED_0
    EXCLUDED_10
    EXCLUDED_18
    EXCLUDED_20
    EXCLUDED_22
    INCLUDED
    INCLUDED_0
    INCLUDED_10
    INCLUDED_18
    INCLUDED_20
    INCLUDED_22
    MIXED
    NA
    EXCLUDED_5
    EXCLUDED_7
    EXCLUDED_NA
    INCLUDED_5
    INCLUDED_7
    INCLUDED_NA
}

type User {
    email: String
    id: Long
    login: String
    notificationEmails: [String]
    organization: Organization
    organizations: [Organization]
    personName: PersonName
    personNames: [PersonName]
    phone: String
    position: String
    title: String
    chief: User
    dateCreated: Long
    groups: [Group]
}

type PersonName {
    dateOfBirth: Long
    firstName: String
    lastName: String
    middleName: String
    id: Long
}

type Organization {
    department: Boolean
    departmentTopOrganization: Organization
    email: String
    id: Long
    inn: String @deprecated(reason: "use 'taxCode' instead")
    kpp: String
    ogrn: String @deprecated(reason: "use 'registrationCode' instead")
    phone: String
    representatives: [User]
    taxCode: String
    taxCodeTitle: String
    title: String
    topSuperOrganization: Organization
    types: [OrganizationType]
}

type OrganizationType {
    code: String
    id: Long
    title: String
}

type TradeStatus {
    code: String
    id: Long
    title: String
}

type Currency {
    code: String
    id: Long
    letterCode: String
    rateGrowPercent: BigDecimal
    title: String
    digitalCode: String
}

input AuthenticateDtoInput {
    captchaResponse: String
    login: String
    password: String
    personalDataAgreementAccept: Boolean
    signature: String
}

type AuthenticatePayload {
    error: String
    jwtToken: String
    personalDataAgreementAcceptanceUpdateRequired: Boolean
    result: AuthenticationResult
    success: Boolean
    currentUserId: Long
}

enum AuthenticationResult {
    FAILURE
    NEED_ONE_TIME_TOKEN_CODE
    SUCCESS
}

input TradeQueryDtoInput {
    request: Boolean
    status: SingularValueMatchDto_TradeStatusDtoInput
}

type PartialResults_Trade {
    items: [Trade]
    limit: Int
    skipped: Int
    total: Int
}

input SingularValueMatchDto_TradeStatusDtoInput {
    mode: SingularValueMatchMode!
    values: [TradeStatusDtoInput]!
}

input TradeStatusDtoInput {
    code: String
    id: Long
}

enum SingularValueMatchMode {
    IN
    NOT_IN
    NOT_NULL
    NULL
    NULL_OR_IN
}

scalar Long
scalar BigDecimal
scalar Instant
